# Generated by Django 6.0.1 on 2026-01-27 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(help_text='URL ya picha ya tangazo', max_length=500)),
                ('target_program', models.CharField(choices=[('Morning Show', 'Morning Show'), ('Mid-Morning Mix', 'Mid-Morning Mix'), ('Habari za Mchana', 'Habari za Mchana'), ('Afternoon Gospel', 'Afternoon Gospel'), ('Drive Time', 'Drive Time'), ('Evening Gospel', 'Evening Gospel'), ('Late Night Mix', 'Late Night Mix'), ('General', 'General (All Programs)')], default='General', help_text='Kipindi ambacho tangazo linaonyeshwa', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('display_duration', models.IntegerField(default=30, help_text='Muda wa kuonyesha tangazo (sekunde)')),
                ('advertiser', models.CharField(max_length=200)),
                ('advertiser_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('advertiser_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('call_to_action', models.CharField(blank=True, max_length=100, null=True)),
                ('external_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled')], default='active', max_length=20)),
                ('impressions', models.IntegerField(default=0, help_text='Idadi ya kuonyeshwa')),
                ('clicks', models.IntegerField(default=0, help_text='Idadi ya kubofya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
