# Generated by Django 6.0.1 on 2026-01-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_created_by_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='target_program',
            field=models.CharField(choices=[('SUN RISE', 'SUN RISE'), ('KR MORNING', 'KR MORNING'), ('HABARI KWA UFUPI', 'HABARI KWA UFUPI'), ('JAMVI LETU', 'JAMVI LETU'), ('HABARI KAMILI MCHANA', 'HABARI KAMILI MCHANA'), ('GOSPEL REVIVAL HUB', 'GOSPEL REVIVAL HUB'), ('SUN SET DRIVE TIME', 'SUN SET DRIVE TIME'), ('SPORTS COUNTER', 'SPORTS COUNTER'), ('HABARI ZA USIKU', 'HABARI ZA USIKU'), ('TUJIFUNZE BIBLIA', 'TUJIFUNZE BIBLIA'), ('USIKU WA USHINDI', 'USIKU WA USHINDI'), ('HABARI ZA USIKU (MARUDIO)', 'HABARI ZA USIKU (MARUDIO)'), ('General', 'General (All Programs)')], default='General', help_text='Kipindi ambacho tangazo linaonyeshwa', max_length=50),
        ),
    ]
