# Generated by Django 6.0.1 on 2026-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL ya picha ya tangazo', max_length=500, null=True),
        ),
    ]
