# Generated by Django 6.0.1 on 2026-02-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_advertisement_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image_url',
        ),
    ]
